# Spring will read both application.properties and application.yml files on start up
guru:
  jms:
    username: JMS Username
    password: nopassword
    url: Some URL
    
--- # file separator
spring:
  profiles: de
guru:
  jms:
    username: JMS in German under 'de' profile